name: gun_web
description: Adavanced webview
version: 0.0.1
author: Velmurugan

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html:
  youtube_player_flutter: ^7.0.0+7
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

